version: '3.1'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/kedro-backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./frontend/requirements:/requirements
      - ./frontend/app:/app
    depends_on:
      - backend
