version: '3.1'
services:
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 8501:8501
      volumes:
        - ./frontend/app:/app
      depends_on:
        - backend

    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      volumes:
        - ./backend/app:/app

