swagger: "2.0"
info:
  description: This is the swagger file that timeseries app
  version: "1.0.0"
  title: Swagger Timeseries
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /tickerlist:
    get:
      operationId: "tier1.tickerlist.read"
      tags:
        - "tickerlist"
      summary: "The tickerlist data structure supported by the server application"
      description: "Read the tickerlist as obtained from Wikipedia"
      responses:
        200:
          description: "Successful read tickerlist operation"
          schema:
            type: "array"
            items:
              type: "string"
  /cron:
    get:
      operationId: "run_cron.get_todays_data"
      tags:
        - "cron"
      summary: "Execute the job of getting today's data update"
      description: "Read the tickerlist as obtained from Wikipedia"
      responses:
        200:
          description: "Successful read tickerlist operation"
          schema:
            type: "array"
            items:
              type: "string"
  /plot/{selection}/{plottype}:
    get:
      operationId: "tier1.selection_plot.read"
      tags:
        - "selection_plot"
      summary: "The selection_plot data structure supported by the server application"
      description: "Read the selection_plot with data obtained from quandl"

      parameters:
        - name: selection
          in: path
          description: selection name such as 'FSE?BAYN.DE_X' or'FSE?BEI.DE_X'. Remark \
            the corresponding Quandl Tickers are 'FSE/BAYN.DE_X' or'FSE/BEI.DE_X'
          type: string
          required: True

        - name: plottype
          in: path
          description: plottype such as scatter, returns or histogram
          type: string
          required: True

      responses:
        200:
          description: "Successful read selection_plot operation"
          schema:
            type: "array"
            items:
              properties:
                data:
                  type: "array"
                layout:
                  type: "array"
